# Generated by Django 5.0.4 on 2025-05-26 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professeurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='professeurs.professeur')),
            ],
        ),
    ]
