# Generated by Django 5.0.4 on 2025-05-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0001_initial'),
        ('niveaux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='niveaux',
            field=models.ManyToManyField(related_name='matieres', to='niveaux.niveau'),
        ),
    ]
