# Generated by Django 5.0.4 on 2025-05-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveau',
            name='matiere',
        ),
    ]
